version: "3.9"

services:
  django:
    build:
      dockerfile: Dockerfile
    container_name: myproject
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9000:9000"
    restart: unless-stopped
    entrypoint:
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:9000"

  mydb:
    hostname: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=myproject
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456

    healthcheck:
      test: [ "CMD-SHELL", "echo 'SELECT 1;' | psql -U postgres -d myproject" ]
      interval: 3s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
    driver: local
