# Generated by Django 3.2.25 on 2024-05-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
