# Generated by Django 3.2.25 on 2024-05-14 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='commissions',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='common_ecology_coeff',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='crime_coeff',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='district',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='floors_count',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='green_spaces_coeff',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='house',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='link',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='negative_impact_coeff',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='phone_nets_coeff',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='population_density_coeff',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='price_per_m2',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='price_per_month',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='region',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='street',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='total_meters',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='underground',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='price',
        ),
        migrations.AddField(
            model_name='flat',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='flat',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='flat',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lobby',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lobby',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lobby',
            name='lobby_type',
            field=models.CharField(choices=[('male', 'Мужское'), ('female', 'Женское')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='lobby',
            name='max_people',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='name',
            field=models.CharField(default='Новое Лобби', max_length=255),
        ),
    ]
