# Generated by Django 3.2.25 on 2024-05-24 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_lobby_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='description',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='lobby_type',
            field=models.CharField(choices=[('male', 'Мужское'), ('female', 'Женское'), ('none', 'Смешанное')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='max_people',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='name',
            field=models.CharField(default='Новое Лобби', max_length=60),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='password',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
