# Generated by Django 3.2.25 on 2024-05-14 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20240514_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='price',
        ),
        migrations.AddField(
            model_name='flat',
            name='link',
            field=models.URLField(default='https://example.com'),
        ),
        migrations.AddField(
            model_name='flat',
            name='lobby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='myapp.lobby'),
        ),
        migrations.AddField(
            model_name='flat',
            name='price_per_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flat',
            name='total_meters',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='flat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='max_people',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='name',
            field=models.CharField(default='Новое Лобби', max_length=100),
        ),
    ]
